spring:
  application:
    name: backend

  datasource:
    url: jdbc:mysql://mysql:3306/db?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&connectionCollation=utf8mb4_unicode_ci
    username: rootTESTE
    password: "senha_forte#101"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always

  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

server:
  address: 0.0.0.0

  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  error:
    include-message: always
    include-binding-errors: always

# jwt:
#   validity: ${JWT_VALIDITY}
#   secret: ${JWT_SECRET}


jwt:
  validity: 3600000
  secret: RXhpc3RlIHVtYSB0ZW9yaWEgcXVlIGRpeiBxdWUsIHNlIHVtIGRpYSBhbGd16W0gZGVzY29icmlyIGV4YXRhbWVudGUgcGFyYSBxdWUgc2VydmUgbyBVbml2ZXJzbyBlIHBvciBxdWUgZWxlIGVzdOEgYXF1aSwgZWxlIGRlc2FwYXJlY2Vy4SBpbnN0YW50YW5lYW1lbnRlIGUgc2Vy4SBzdWJzdGl0de1kbyBwb3IgYWxnbyBhaW5kYSBtYWlzIGVzdHJhbmhvIGUgaW5leHBsaWPhdmVsLiBFeGlzdGUgdW1hIHNlZ3VuZGEgdGVvcmlhIHF1ZSBkaXogcXVlIGlzc28gauEgYWNvbnRlY2V1Li4u